### ISSUE TITLE
error while install

### ISSUE THREAD

**Issue by suedar** [pagarme/node-rsa-keygen#7]
``` js
> rsa-keygen@1.0.6 install /usr/local/lib/node_modules/rsa-keygen
> node-gyp rebuild

  CXX(target) Release/obj.target/rsa_keygen/src/rsa_keygen.o
In file included from ../src/rsa_keygen.cc:2:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet'
      in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/rsa_keygen.cc:2:
../node_modules/nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:176:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/rsa_keygen.cc:2:
../node_modules/nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:169:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/rsa_keygen.cc:2:
../node_modules/nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:162:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/rsa_keygen.cc:2:
../node_modules/nan/nan.h:1457:31: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:176:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sunchao15/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/rsa_keygen.cc:58:26: error: no matching member function for call to
      'ToInt32'
                modulusBits = info[0]->ToInt32()->Value();
                              ~~~~~~~~~^~~~~~~
/Users/sunchao15/.node-gyp/10.16.0/include/node/v8.h:2437:43: note: candidate
      function not viable: requires single argument 'context', but no arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/v8.h:2450:30: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
                Local<Int32> ToInt32(Isolate* isolate) const);
                             ^
../src/rsa_keygen.cc:62:23: error: no matching member function for call to
      'ToInt32'
                exponent = info[1]->ToInt32()->Value();
                           ~~~~~~~~~^~~~~~~
/Users/sunchao15/.node-gyp/10.16.0/include/node/v8.h:2437:43: note: candidate
      function not viable: requires single argument 'context', but no arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/sunchao15/.node-gyp/10.16.0/include/node/v8.h:2450:30: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
                Local<Int32> ToInt32(Isolate* isolate) const);
                             ^
4 warnings and 3 errors generated.
make: *** [Release/obj.target/rsa_keygen/src/rsa_keygen.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rsa-keygen
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsa-keygen@1.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rsa-keygen@1.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunchao15/.npm/_logs/2019-08-28T08_31_40_809Z-debug.log
```

**Comment by bilegole** [comment]
same for me
